BITFSRC	    :=  https://raw.githubusercontent.com/Horolsky/bitf/master/src/bitf.hpp

bitf.hpp:
	@echo "The bitf.hpp file does not exist! Run 'make update' to download it."
	exit 1

update:
	wget $(BITFSRC)
